### ISSUE TITLE
Add spec parameter for use_ssl

### ISSUE THREAD

**Issue by elnappo** [bosh-elastic-stack/curator-boshrelease#2]
I have a ElasticsSearch cluster which is only reachable over TLS. I would like to add a spec parameter for `use_ssl`. Is this okay for you? If so, I would create a PR for this.

**Comment by making** [comment]
Yes. Making [these](https://github.com/bosh-elastic-stack/curator-boshrelease/blob/master/jobs/curator/templates/config/config.yml#L17-L19) configurable makes sense.
